name: dart-sass-convert
description: Command line application for transforming SASS syntax to SCSS syntax (and maybe more in future).
version: 1.0.0

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  build_runner: ^2.1.0
  build_test: ^2.1.0
  build_web_compilers: ^3.0.0
dependencies: 
  sass_api: ^1.0.0-beta.38

executables:
  sass2scss: