name: Dart Build CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Build
        run: dart compile exe -o sass2scss_${{matrix.os}}.exe bin/sass_tools.dart

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: sass2scss_${{matrix.os}}
          path: sass2scss_${{matrix.os}}.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: sass2scss_${{matrix.os}}.exe
